version: '3'

services:
  webserver1:
    build: .
    command: ["python3", "server.py", "0.0.0.0", "80", "/Code/cert.pem", "/Code/key.pem"]
    networks:
      - internal

  webserver2:
    build: .
    command: ["python3", "server.py", "0.0.0.0", "80", "/Code/cert.pem", "/Code/key.pem"]
    networks:
      - internal

  nginx-proxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Code/cert.pem:/etc/nginx/certs/cert.pem:ro
      - ./Code/key.pem:/etc/nginx/certs/key.pem:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge